# Included before project(): the toolchain must be selected before compiler checks.
set_property(CACHE ROOTLINK_TARGET PROPERTY STRINGS ubuntu rv1106)
if(NOT ROOTLINK_TARGET MATCHES "^(ubuntu|rv1106)$")
  message(FATAL_ERROR "ROOTLINK_TARGET must be ubuntu or rv1106")
endif()
if(DEFINED ROOTLINK_CONFIGURED_TARGET AND
   NOT ROOTLINK_CONFIGURED_TARGET STREQUAL ROOTLINK_TARGET)
  message(FATAL_ERROR "Target changed from ${ROOTLINK_CONFIGURED_TARGET} to ${ROOTLINK_TARGET}. Use a separate build directory for each target.")
endif()
if(EXISTS "${CMAKE_BINARY_DIR}/CMakeCache.txt" AND NOT DEFINED ROOTLINK_CONFIGURED_TARGET)
  message(FATAL_ERROR "This directory uses the legacy build configuration. Use a new build directory with config/build.cmake.")
endif()
set(ROOTLINK_CONFIGURED_TARGET "${ROOTLINK_TARGET}" CACHE INTERNAL "Configured target")
set(ROOTLINK_AUDIO_API "alsa" CACHE STRING "Audio backend" FORCE)
set(ROOTLINK_SERVICE_API "curl" CACHE STRING "Service backend" FORCE)
if(ROOTLINK_TARGET STREQUAL "rv1106")
  set(CMAKE_TOOLCHAIN_FILE "${CMAKE_CURRENT_LIST_DIR}/rv1106-toolchain.cmake"
      CACHE FILEPATH "RV1106 toolchain" FORCE)
  set(ROOTLINK_UI_BACKEND "fbdev" CACHE STRING "Display backend" FORCE)
  set(ROOTLINK_DEFAULT_CAPTURE_DEVICE "default" CACHE STRING "Capture device" FORCE)
  set(ROOTLINK_DEFAULT_PLAYBACK_DEVICE "default" CACHE STRING "Playback device" FORCE)
  set(BUILD_TESTING OFF CACHE BOOL "Native tests" FORCE)
else()
  if(CMAKE_TOOLCHAIN_FILE)
    message(FATAL_ERROR "The ubuntu target uses the native compiler; remove the toolchain setting and use a fresh build directory.")
  endif()
  set(ROOTLINK_UI_BACKEND "sdl" CACHE STRING "Display backend" FORCE)
  set(ROOTLINK_DEFAULT_CAPTURE_DEVICE "pulse" CACHE STRING "Capture device" FORCE)
  set(ROOTLINK_DEFAULT_PLAYBACK_DEVICE "pulse" CACHE STRING "Playback device" FORCE)
  set(BUILD_TESTING ON CACHE BOOL "Native tests" FORCE)
endif()
message(STATUS "RootLink target: ${ROOTLINK_TARGET}; audio: alsa; services: curl; UI: ${ROOTLINK_UI_BACKEND}")
