#ifndef ROOTLINK_LV_CONF_H
#define ROOTLINK_LV_CONF_H
#define LV_COLOR_DEPTH 16
#define LV_USE_OS LV_OS_NONE
#define LV_USE_STDLIB_MALLOC LV_STDLIB_CLIB
#define LV_USE_STDLIB_STRING LV_STDLIB_CLIB
#define LV_USE_STDLIB_SPRINTF LV_STDLIB_CLIB
#define LV_USE_LOG 0
#define LV_USE_THEME_DEFAULT 0
#define LV_USE_THEME_SIMPLE 0
#define LV_USE_THEME_MONO 0
#define LV_FONT_MONTSERRAT_48 1
#define LV_USE_SYSMON 0
#define LV_USE_SDL ROOTLINK_LV_SDL
#define LV_SDL_DIRECT_EXIT 0
#define LV_SDL_ACCELERATED 0
#define LV_SDL_BUF_COUNT 1
#define LV_SDL_INCLUDE_PATH <SDL2/SDL.h>
#define LV_USE_LINUX_FBDEV 0
#define LV_USE_LINUX_DRM 0
#define LV_USE_EVDEV 0
#define LV_USE_THORVG_INTERNAL 0
#define LV_BUILD_EXAMPLES 0
#endif
